### ISSUE TITLE
Feed Visualization with external data

### ISSUE THREAD

**Issue by senj** [etishor/Metrics.NET.FlotVisualization#3]
Hello,
I have a question,

Is it possible to aggregate metrics from multiple services and feed them into one instance of Metrics.NET on a single page?
I already set up my services to aggregate metrics in JSON format, so how can i put this data into Metrics.NET to show all my diagramms on one page.

May this be the way to go?
https://github.com/etishor/Metrics.NET/blob/master/Src/Metrics.Central/MetricsService.cs

Greetings

**Comment by etishor** [comment]
Hi,

You are correct, that is what Metrics.Central is meant to do. It is functional but unfortunately it is still very much work in progress at the moment.

If you need to gather and aggregate metrics from multiple services there is also the option of sending  them to graphite and using the graphite/graphana viewer. Setting them up is far from trivial unfortunately.

**Comment by senj** [comment]
Yes, especially in Windows, that's the reason I want to try it that way.
It already works to some extend, there are only some mismatches with the json types i will resolve now.
Thanks for your answer.
